title: "Gaurav Writes"
author: "Gaurav"
description: "The personal blog of Gaurav. Thoughts on the philosophy of potatoes and everything in between."
url: "https://gauravwrites.com" # Setting this now prepares your links for the domain
permalink: /:title/
lang: "en"
excerpt_separator: "<!--more-->"
date_format: "%B %d, %Y"

# Layout
show_excerpts: true
show_frame: false
show_sidebar: false
show_minimal: false

# Menu
navigation:
  - {url: "/archive/", title: "Archive"}
  - {url: "/about/", title: "About Me"}

external:
  - {title: Mail, icon: envelope, url: "mailto:write@gauravwrites.com"}
  - {title: Mastodon, icon: mastodon, url: "https://mastodon.social/@gauravwrites"}

# SEO & Discovery
plugins:
  - jekyll-feed
  - jekyll-seo-tag # Add this! It's the gold standard for Google discovery
